export const en = {
  home: {
    manualOperationMode: 'Manual Operation Mode',
    createMenu: 'Tạo Thực Đơn',
  },
  product: {
    customProduct: 'Tuỳ Chỉnh Món Ăn',
    custom: 'Tuỳ Chỉnh',
    addCustomProduct: 'Thêm Lựa Chọn',
    addProduct: 'Thêm Món',
  },

  ingredient: {
    search: 'Tìm kiếm nguyên liệu',
  },
  cart: {
    cart: 'Giỏ Hàng',
    payment: 'Thanh Toán',
    mainDishes: 'Món chính',
    ingedients: 'Nguyên liệu',
    amountQuality: 'Số lượng: {number}',
  },
  order: {
    success: 'Đơn hoàn thành',
    error: 'Đặt hàng thất bại',
    done: 'Đã hoàn thành',
    pending: 'Đang Chuẩn bị',
    message: 'Ghi Chú',
    create: 'Đơn hàng đã được tạo',
    paid: 'Đơn hàng đã thanh toán',
  },
  common: {
    quick: 'Quick',
    serve: 'Serve',
    contactUs: 'Contact Us',
    searchMenu: 'Tìm kiếm thực đơn',
    noData: 'No Data',
    numberCal: '{number} Cal',
    quality: 'Số lượng: {number}',
    calo: 'lượng calo: {number}/100g',
    vnd: '{number} đ',
    order: 'Đặt hàng',
    phoneNumber: 'Số điện thoại',
    fullName: 'Họ Và Tên',
    confirm: 'Xác Nhận',
  },
  login: {
    signUp: 'Đăng Ký',
    welcomeTo: 'Welcome to',
    youHaveAccount: 'Đã có tài khoản',
    younotAccount: 'Chưa có tài khoản',
    email: 'Email',
    password: 'Password',
    backIndex: 'Quay lại trang chủ',
  },
  signup: {
    email: 'Email',
    password: 'Password',
    userName: 'Tên tài khoản',
    name: 'Tên người dùng',
    backIndex: 'Quay lại trang chủ',
  },
  setting: {
    setting: 'Setting',
    logout: 'Logout',
    login: 'Login',
    historyproduct: 'Lịch Sử Đơn Hàng',
    historyOrderStaff: 'Lịch Sử Hóa đơn cửa hàng',
    userHistoryProduct: 'Lịch Sử Mưa Hàng',
    bill: 'Đơn hàng',
    profile: 'Thông tin cá nhân',
  },
  action: {
    off: 'Off',
    on: 'ON',
    stopAll: 'Stop All',
    switchInterface: 'Switch Interface',
    runningPrograms: 'Running Programs',
    runningStations: 'Running Stations',
    runByProgram: 'Run by Program',
    runByStation: 'Run by Station',
    flowMonitor: 'Flow Monitor',
    diagnosticsStatus: 'Diagnostics/Status',
    notifications: 'Notifications',
  },

  error: {
    requireEmail: 'Email không được để trống',
    requirePassword: 'Password không được để trống',
    requireName: 'Tên người dùng không được để trống',
    requireUserName: 'Tên tài khoản không được để trống',
  },
};
