export const en = {
  home: {
    manualOperationMode: 'Manual Operation Mode',
    createMenu: 'Tạo Thực Đơn',
  },
  product: {
    customProduct: 'Tuỳ Chỉnh Món Ăn',
    custom: 'Tuỳ Chỉnh',
    addCustomProduct: 'Thêm Lựa Chọn',
    addProduct: 'Thêm Món',
  },

  ingredient: {
    search: 'Tìm kiếm nguyên liệu',
  },
  cart: {
    cart: 'Giỏ Hàng',
    payment: 'Thanh Toán',
    mainDishes: 'Món chính',
    ingedients: 'Nguyên liệu',
    amountQuality: 'Số lượng: {number}',
  },
  order: {
    error: 'Đặt hàng thất bại',
    message:
      'Để đảm bảo trải nghiệm mua sắm suôn sẻ và bảo vệ quyền lợi của mình, quý khách vui lòng đọc kỹ chính sách đặt hàng và hoàn tiền trước khi mua. Cảm ơn quý khách đã tin tưởng sử dụng dịch vụ của QuickServe!',
    done: 'Đã hoàn thành',
    pending: 'Đơn hàng vừa được tạo',
    paided: 'Đơn hàng đã thanh toán',
    preparing: 'Đơn hàng đang chuẩn bị',
    success: 'Đơn hàng đã hoàn thành!',
    got: 'Đơn đã được lấy',
    canceled: 'Đơn đã bị hủy',
    refund: 'Đơn hoàn tiền lại',
    failed: 'Đơn hàng thất bại',
  },
  common: {
    quick: 'Quick',
    serve: 'Serve',
    contactUs: 'Contact Us',
    searchMenu: 'Tìm kiếm thực đơn',
    noData: 'No Data',
    numberCal: '{number} Cal',
    quality: 'Số lượng: {number}',
    calo: 'lượng calo: {number}/100g',
    vnd: '{number} đ',
    order: 'Đặt hàng',
    phoneNumber: 'Số điện thoại',
    fullName: 'Họ Và Tên',
    confirm: 'Xác Nhận',
  },
  login: {
    signUp: 'Đăng Ký',
    welcomeTo: 'Welcome to',
    youHaveAccount: 'Đã có tài khoản',
    younotAccount: 'Chưa có tài khoản',
    email: 'Email',
    password: 'Password',
    backIndex: 'Quay lại trang chủ',
  },
  signup: {
    email: 'Email',
    password: 'Password',
    userName: 'Tên tài khoản',
    name: 'Tên người dùng',
    backIndex: 'Quay lại trang chủ',
  },
  setting: {
    setting: 'Setting',
    logout: 'Logout',
    login: 'Login',
    historyproduct: 'Lịch Sử Đơn Hàng',
    historyOrderStaff: 'Lịch Sử Hóa đơn cửa hàng',
    userHistoryProduct: 'Lịch Sử Mưa Hàng',
    bill: 'Đơn hàng',
    profile: 'Thông tin cá nhân',
    OrderPolicy: 'Chính sách đặt hàng',
  },
  action: {
    off: 'Off',
    on: 'ON',
    stopAll: 'Stop All',
    switchInterface: 'Switch Interface',
    runningPrograms: 'Running Programs',
    runningStations: 'Running Stations',
    runByProgram: 'Run by Program',
    runByStation: 'Run by Station',
    flowMonitor: 'Flow Monitor',
    diagnosticsStatus: 'Diagnostics/Status',
    notifications: 'Notifications',
  },

  error: {
    requireEmail: 'Email không được để trống',
    requirePassword: 'Password không được để trống',
    requireName: 'Tên người dùng không được để trống',
    requireUserName: 'Tên tài khoản không được để trống',
  },
};
